name: Deploy

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  deploy:
    name: Deploy

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full Git history


